sudo: false

language: go

go:
  - '1.12.x'

services:
  - docker

notifications:
  email: false

branches:
  only:
    - master

cache:
  directories:
  - $GOPATH/pkg/mod

before_script:
  - go get -u golang.org/x/lint/golint

script:
  - make build
