sudo: false

language: golang

go:
  - '1.12.x'

notifications:
  email: false

branches:
  only:
    - master

before_script:
  - go get -u golang.org/x/lint/golint

script:
  - make build

cache:
  directories:
    - $HOME/.cache/go-build        # Cache the binaries
    - $HOME/gopath/pkg/mod         # Cache the Go modules
